---
- name: Ensure mysql dirs exist
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ mysql_user }}"
    group: "{{ mysql_user }}"
    recurse: yes
  with_items:
    - "{{ mysql_backups_dir }}"
    - "{{ mysql_conf_dir }}"
    - "{{ mysql_lib_dir }}"

- name: Copy mysql config files
  template:
    src: "{{ item }}"
    dest: "{{ mysql_conf_dir }}/{{ item }}"
    force: yes
    owner: "{{ mysql_user }}"
    group: "{{ mysql_user }}"
  with_items:
    - "character_set.cnf"

